import SiteFooter from "@/components/SiteFooter";
import { Link } from "wouter";
import { ArrowDownRight, ArrowUpRight, Check, Gauge, Layers3, ShieldCheck, UsersRound, Workflow } from "lucide-react";
import ServicesHeader from "@/components/ServicesHeader";

const models = [
  { number: "01", icon: UsersRound, title: "Dedicated AI teams", kicker: "Your team, extended", description: "Build a focused team around your data and AI roadmap. Get specialists who learn your domain, tools, quality bar, and way of working.", bestFor: "Long-term programs and complex domain work", includes: ["Dedicated project and delivery leadership", "Domain-trained data specialists", "Embedded QA and reporting", "Flexible scope as priorities evolve"] },
  { number: "02", icon: Gauge, title: "Workforce scaling", kicker: "Capacity when you need it", description: "Add reliable capacity for peaks, launches, backlogs, or new workflows without the overhead of hiring and managing every role yourself.", bestFor: "Seasonal volume, pilots, and rapid growth", includes: ["On-demand team expansion", "Ramp-up and ramp-down flexibility", "Multi-shift delivery coverage", "Transparent volume-based planning"] },
  { number: "03", icon: ShieldCheck, title: "Quality assurance", kicker: "Confidence in every output", description: "Put a specialist quality layer around your existing operations with structured review, sampling, validation, and continuous improvement.", bestFor: "High-stakes data and accuracy-critical workflows", includes: ["Multi-level review and sampling", "Custom quality rubrics", "Error analysis and feedback loops", "Audit-ready performance reporting"] },
  { number: "04", icon: Workflow, title: "Managed AI operations", kicker: "The full operating layer", description: "Hand over a complete workflow—from intake and annotation to evaluation and reporting—while you stay focused on the model and the outcome.", bestFor: "End-to-end programs and production operations", includes: ["Workflow design and orchestration", "People, process, and tooling", "Security-minded delivery operations", "Continuous optimization and governance"] },
];

const compare = [["Dedicated AI teams", "When you need depth, continuity, and a partner who learns the work."], ["Workforce scaling", "When volume changes faster than your internal capacity."], ["Quality assurance", "When the cost of an incorrect record, label, or decision is high."], ["Managed AI operations", "When you want one accountable partner from intake to outcome."]];

export default function EngagementModels() {
  return <div className="engagement-page"><div className="announcement-bar"><span className="mono-label announcement-label">DELIVERY / FLEXIBILITY / CONTROL</span><span>The right operating model for the work ahead.</span><a href="/contact-us" className="announcement-link">Talk to our team <ArrowUpRight size={14} /></a></div><ServicesHeader />
    <main><section className="engagement-hero section-pad"><div className="engagement-hero-copy"><Link href="/" className="back-link"><ArrowUpRight size={15} className="back-icon" /> Home</Link><span className="mono-label accent-label">ENGAGEMENT MODELS / HOW WE WORK TOGETHER</span><h1>Choose the support that <em>fits your ambition.</em></h1><p>From a specialist team to a fully managed AI operation, we make it easier to access the people, process, and precision your data program needs.</p><div className="hero-actions"><a className="button button-primary" href="/contact-us">Find your model <ArrowUpRight size={17} /></a><a className="text-link" href="#models">Explore models <ArrowDownRight size={17} /></a></div></div><div className="engagement-hero-art"><div className="engagement-art-grid" /><div className="engagement-art-core"><Layers3 size={42} strokeWidth={1.2} /><span className="mono-label">RIGHT-SIZED DELIVERY</span></div><div className="engagement-orbit orbit-a" /><div className="engagement-orbit orbit-b" /><span className="engagement-art-label mono-label">EDS / OPERATING MODEL 01</span></div></section>
      <section id="models" className="model-list-section section-pad section-white"><div className="section-heading split-heading"><div><span className="mono-label accent-label">Four ways to work with us</span><h2>One quality bar. <span>Four ways in.</span></h2></div><p>Every model is built around the same promise: accurate work, secure operations, and clear accountability. Choose the shape that matches your stage and scale.</p></div><div className="engagement-model-grid">{models.map((model) => { const Icon = model.icon; return <article className="engagement-model-card" key={model.number}><div className="engagement-card-top"><span className="mono-label">{model.number}</span><Icon size={23} strokeWidth={1.5} /></div><span className="engagement-kicker">{model.kicker}</span><h3>{model.title}</h3><p>{model.description}</p><div className="best-for"><span className="mono-label">BEST FOR</span><strong>{model.bestFor}</strong></div><ul>{model.includes.map((item) => <li key={item}><Check size={14} />{item}</li>)}</ul><a href="/contact-us" className="category-card-link">Talk about this model <ArrowUpRight size={15} /></a></article>; })}</div></section>
      <section className="engagement-principles section-pad"><div className="principles-heading"><span className="mono-label accent-label">What stays constant</span><h2>Flexible on the surface.<br /><span>Consistent underneath.</span></h2></div><div className="principles-list"><div><span className="mono-label">01 / PRECISION</span><h3>Multi-level quality checks</h3><p>Every workflow has a defined quality bar, review loop, and accountable owner.</p></div><div><span className="mono-label">02 / SECURITY</span><h3>Security-minded operations</h3><p>Confidential information is handled with controlled access and compliance-ready processes.</p></div><div><span className="mono-label">03 / EFFICIENCY</span><h3>Built to improve over time</h3><p>We measure throughput, errors, and turnaround so the operation gets better with every cycle.</p></div></div></section>
      <section className="fit-section section-pad section-grey"><div className="section-heading split-heading"><div><span className="mono-label accent-label">Find your fit</span><h2>Start with the problem.<br /><span>We&apos;ll shape the model.</span></h2></div><p>Not sure where you belong? That is normal. We can start with your workflow, volume, deadlines, and quality requirements, then recommend the right combination of support.</p></div><div className="fit-table">{compare.map(([title, detail], index) => <a href="/contact-us" key={title}><span className="mono-label">0{index + 1}</span><strong>{title}</strong><span>{detail}</span><ArrowUpRight size={17} /></a>)}</div></section>
      <section id="contact" className="engagement-contact section-pad"><span className="mono-label contact-label">READY WHEN YOU ARE</span><h2>Build the right team<br />for the <em>work ahead.</em></h2><p>Tell us what you need to deliver, and we&apos;ll help you find the cleanest way to get there.</p><a className="button button-dark" href="mailto:info@edatashop.com?subject=Engagement%20Models%20-%20Let's%20talk">info@edatashop.com <ArrowUpRight size={18} /></a></section></main>
      <SiteFooter /></div>;
}
