import { ChevronDown } from "lucide-react";
import { Link } from "wouter";
import ServicesHeader from "@/components/ServicesHeader";
import SiteFooter from "@/components/SiteFooter";

const groups = [
  { title: "Working with DataShop", items: [["What does DataShop do?", "DataShop is the data and AI services brand of CyberData India. We help organizations collect, digitize, structure, label, transform, validate, and operate information for enterprise systems, research, publishing, analytics, and AI."], ["Where is your team located?", "CyberData India is headquartered at Sanchi Building, 2nd Floor, 77 Nehru Place, New Delhi – 110019, India. We also support North American conversations through our Houston contact."], ["How do we start?", "Send a short enquiry describing your source material, approximate volume, desired output, timeline, and any quality or security requirements. We will recommend a practical next step, often a discovery call or representative sample review."], ["Can you begin with a pilot?", "Yes. A pilot can confirm the interpretation rules, workflow, expected output, quality checks, effort, and scaling approach before a larger production program begins."]]},
  { title: "Services and delivery", items: [["What data types can you work with?", "Depending on the engagement, inputs can include paper documents, scans, PDFs, office files, databases, XML or HTML, images, video, audio, surveys, research records, first-person video, and LiDAR or point-cloud data."], ["Do you support AI data collection and annotation?", "Yes. Current capabilities include image, video, text, audio, egocentric, computer-vision, human-preference, safety, model-evaluation, and 3D annotation workflows. The exact modalities and taxonomy are agreed for each project."], ["Can you handle legacy content and document conversion?", "Yes. Relevant services include OCR and ICR cleanup, document conversion, XML and SGML markup, HTML conversion, CAD conversion, metadata enrichment, indexing, digitization, data cleansing, and structured content transformation."], ["Which engagement models are available?", "Projects can be delivered through dedicated AI teams, workforce scaling, independent quality assurance, or managed AI operations. The right model depends on volume, duration, workflow ownership, and integration needs."], ["Can the workflow integrate with our tools?", "Where technically and contractually appropriate, workflows can be designed around your platforms, annotation tools, repositories, schemas, APIs, review systems, and delivery formats."]]},
  { title: "Quality, security, and scale", items: [["How is quality managed?", "Quality controls are tailored to the task. They can include documented guidelines, training and calibration, automated validation, sampling, double review, adjudication, exception handling, reconciliation, audit logs, and acceptance reporting."], ["What security standards do you follow?", "CyberData India identifies itself as ISO 9001:2015 and ISO 27001:2013 certified. Project-specific access, transfer, confidentiality, retention, and environment requirements should be documented in the engagement agreement."], ["How do you handle confidential project data?", "Do not send sensitive production data through a general web form. We first agree secure transfer, access, storage, processing, retention, and deletion procedures appropriate to the project."], ["Can teams and volumes scale?", "Yes. The delivery approach can combine trained specialists, project leads, quality teams, automation, and documented workflows. Scaling plans are shaped around forecast volume, turnaround, language, domain expertise, and quality requirements."]]},
  { title: "Commercial and project questions", items: [["How is pricing calculated?", "Pricing depends on input condition, data type, complexity, volume, turnaround, languages, required expertise, quality method, tools, security controls, and output specifications. We review these factors before providing an estimate."], ["What information should we include in an enquiry?", "Please include the service or outcome required, representative input type, estimated volume, desired format, target timeline, required accuracy or acceptance criteria, languages or domains, and any security constraints."], ["Do you provide samples or references?", "Relevant case studies are available on this website. Additional examples, pilot outputs, or references may be discussed where confidentiality and customer permissions allow."], ["How quickly will someone respond?", "The website forms indicate a typical response within one business day. Complex enquiries may require a follow-up discussion before we can recommend the right workflow."]]}
];

export default function FAQ() {
  return <div className="faq-page"><ServicesHeader /><main><header className="faq-hero section-pad"><nav><Link href="/">Home</Link><span>/</span><strong>FAQ</strong></nav><span className="mono-label accent-label">QUESTIONS / CLEAR ANSWERS</span><h1>Frequently asked<br /><em>questions.</em></h1><p>Practical answers about our services, engagement models, data handling, quality, and getting started.</p></header><section className="faq-content section-pad section-white">{groups.map((group, groupIndex) => <section className="faq-group" key={group.title}><div className="faq-group-title"><span className="mono-label">{String(groupIndex + 1).padStart(2, "0")}</span><h2>{group.title}</h2></div><div className="faq-list">{group.items.map(([question, answer]) => <details key={question}><summary>{question}<ChevronDown size={18} /></summary><p>{answer}</p></details>)}</div></section>)}</section><section className="faq-contact section-pad"><span className="mono-label contact-label">STILL HAVE A QUESTION?</span><h2>Tell us what<br /><em>you&apos;re working on.</em></h2><p>We&apos;ll help you identify the right service and a practical next step.</p><Link className="button button-dark" href="/contact-us">Contact our team</Link></section></main><SiteFooter /></div>;
}
